version: '2'

services:
  web:
    image: demo-api
    build: .
    command: npm run start
    ports:
     - "4005:4005"
    depends_on:
     - mongo
  mongo:
    image: mongo
    ports:
     - "27017:27017"